require "saasu/version"
require "saasu/client"
require "saasu/base"
require "saasu/contact"
require "saasu/invoice_attachment"
require "saasu/item"
require "saasu/invoice"
require "saasu/company"
require "saasu/payment"
require "saasu/account"
require "saasu/tax_code"
require "saasu/config"
require "saasu/auth"
require "saasu/search"
require "saasu/user"
require "saasu/file_identity"
require "saasu/contact_aggregate"

module Saasu
end
